### ISSUE TITLE
Is it possible make `go get kubevirt.io/qe-tools` working?

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/qe-tools#10]
I remember that there were same Q regarding to `go get kubevirt` in past.
I am not sure how far it has gone, but I am curious if we can do that for qe-tools project.

My use case is that in kubevirt-ansible we have `glide.yaml` where we have to list this as an dependency although it is already dependency of kubevirt itself & in addition with proper version .

If I remove it from glide.yaml file I fail on
```
[WARN]	Unable to checkout kubevirt.io/qe-tools/pkg/ginkgo-reporters
[ERROR]	Error looking for kubevirt.io/qe-tools/pkg/ginkgo-reporters: https://kubevirt.io/qe-tools/pkg/ginkgo-reporters Not Found
```
I got it working with 
```yaml
package: kubevirt.io/kubevirt-ansible
import:
- package: kubevirt.io/kubevirt
  version: v0.6.3
  repo:    https://github.com/kubevirt/kubevirt.git
- package: kubevirt.io/qe-tools
  repo: https://github.com/kubevirt/qe-tools.git
```
But I would like to remove it entirely from there.
